### ISSUE TITLE
LAZ-perf or LAZ-zip for write

### ISSUE THREAD

**Issue by julienlau** [hobu/laz-perf#113]
Hi,

I am new to these tools, but by reading the README I understand:
- that LAZ-perf makes a performance when reading LAZ especially when reading from a browser.
- it is not clear if LAZ-perf browser features are only available if the LAZ was written initially with LAZperf or if it is also working with any LAZ.
- it is not clear if LAZ-perf is more performant than LASzip (when building LAZ from a LAS for example) ?

Would it be please possible to clarify this and maybe put this details into the README ?

Regards

**Comment by abellgithub** [comment]
>  - that LAZ-perf makes a performance when reading LAZ especially when reading from a browser.

It used to be the case that LAZperf was better when used in a browser but I don't know if this is true anymore. You'd have to test. It could be that improvements in webassebly have eliminated this advantage.

> - that LAZ-perf makes a performance when reading LAZ especially when reading from a browser.

There's nothing special about a LAZ file written with lazperf. The data encoding is necessarily identical.

> - it is not clear if LAZ-perf is more performant than LASzip (when building LAZ from a LAS for example)

I don't think it's much different on standard CPUs/platforms. If there is a performance advantage to LAZperf, it's when used in a browser with web assembly.

**Comment by hobu** [comment]
@abellgithub's history about laz-perf is correct. It was originally developed as an alternative implementation so it worked better when compiling to WASM. Martin changed the implementation of the LASzip library so that particular advantage was not as relevant.

laz-perf does have a few other significant advantages, however:

* It's API is much clearer and easier to use
* It supports multi-threaded reads 
* PDAL is moving to using it exclusively for LAZ support at PDAL 2.4+

With Martin's [recent death](https://lidarmag.com/2021/10/30/in-memoriam-martin-isenburg-1972-2021/), LASzip is likely to move into more of a pure maintenance mode. The LASzip library hadn't changed significantly in a number of years anyway, and LASzip is the implementation inside of all of LAStools. There are no plans to move the compression approach forward in any significant way.

We plan to continue to maintain laz-perf for PDAL and for other WASM consumers like laslaz.js, which is used by Potree, deck.gl and many others.

**Comment by julienlau** [comment]
thanks for the details.

Otherwise, for simple LAS to LAZ conversion I observe PDAL+LASzip being a lot slower than LAStools2.0/las2las64 despite the fact they both use not more than one core.

Is there some plan improving LAZperf writing performance to match these ?

![image](https://user-images.githubusercontent.com/6950247/149555743-053a263b-c0b3-4fc0-85a9-191f0e25befe.png)

**Comment by hobu** [comment]
This is a consequence of PDAL more than laz-perf.

> Is there some plan improving LAZperf writing performance to match these ?

As always, performance patches will always be reviewed 😄

**Comment by julienlau** [comment]
:smile: 
thanks
